---
title: "data_import"
author: "Paula Wu"
date: "9/28/2021"
output: html_document
---

```{r, echo = FALSE, message = FALSE}
library(tidyverse)
library(readxl)
library(haven)
```

## Import some data
I want to import "FAS_litters.csv"
```{r}
litters_df = read_csv("./data/FAS_litters.csv")  # this is a relative path
litters_df = janitor::clean_names(litters_df)

pups_df = read_csv("./data/FAS_pups.csv")
pups_df = janitor::clean_names(pups_df)
```

## Select 
Lect's select some columns
```{r}
select(litters_df, group, litter_number)
select(litters_df, group, gd0_weight, gd18_weight)
select(litters_df, group, gd0_weight:gd_of_birth)  # keep several columns
select(litters_df, group, starts_with("pups"))  # start_with, end_with, contains
select(litters_df, -litter_number)  # except litter_number
select(litters_df, GROUP = group, litter_number)  # you can still rename the attributes (just rename) 
select(litters_df, litter_number, everything())  # relocate the litter_number first, and keep everything later
```
```{r}
names(pups_df)
select(pups_df, litter_number:pd_ears)  # or just litter_number, sex, pd_ears
# pull(litters_df, group)
```

## filter
```{r}
filter(litters_df, gd_of_birth == 20)
filter(litters_df, group == "Con7")

filter(litters_df, gd0_weight > 23)
filter(litters_df, pups_survive != 4)

filter(litters_df, !(group == "Con7"))
filter(litters_df, group %in% c("Con7", "Con8"))  # group in both con7 and con8
filter(litters_df, group == "Con7" & gd_of_birth == 20)  # or: |
```

## drop
```{r}
drop_na(litters_df)
names(litters_df)
drop_na(litters_df, pups_survive)
```

## mutate
Let's change/add/delete columns
```{r}
mutate(
  litters_df, 
  weight_change = (gd18_weight - gd0_weight),
  group = str_to_lower(group))  # capital C/G becomes all lower cases
```

## arrange
rearrange the data
```{r}
arrange(litters_df, gd0_weight)
arrange(litters_df, desc(gd0_weight))
arrange(litters_df, gd_of_birth, gd0_weight)
```
## Pipes
```{r}
litters_data_raw = read_csv("data/FAS_litters.csv")
litters_clean_name = janitor::clean_names(litters_data_raw)
litters_select = select(litters_clean_name, group, pups_survive)
litters_filtered = filter(litters_select, group == "Con7")

litters_df = 
  read_csv("data/FAS_litters.csv") %>%
  janitor::clean_names() %>%
  select(group, group, pups_survive) %>%
  filter(group == "Con7")

litters_df = 
  read_csv("data/FAS_litters.csv") %>% 
  janitor::clean_names() %>%
  select(-pups_survive) %>%
  mutate(
    weight_change = (gd18_weight - gd0_weight),
    group = str_to_lower(group)
  ) %>% 
  drop_na(weight_change) %>% 
  filter(group %in% c("con7", "con8")) %>% 
  select(litter_number, group, weight_change, everything())
```








