---
title: "Simple document"
output: github_document
---

I'm an R Markdown document! 

```{r, echo = FALSE, message = FALSE}
library(tidyverse)
```

## Import some data
I want to import "FAS_litters.csv"
```{r}
litters_df = read_csv("./data/FAS_litters.csv")  # this is a relative path
# don't use absolute path, absolute makes it un-sharable
```
I imported the dataset. Now I need better names. 
```{r}
names(litters_df)
litters_df = janitor::clean_names(litters_df)  # could also import library janitor at the top, but janitor is large
```
Now I have better names. Let's take a look at the dataset.
```{r}
litters_df
head(litters_df, 20)
tail(litters_df, 5)
```
Now I use a lot is:
```{r, eval = FALSE}
view(litters_df)
```

Here is `skimr`:
```{r}
skimr::skim(litters_df)
```

## Arguments in "read_csv"
```{r}
# skip: skip the first 5 lines, don't display column names, set all "Low8" as na
litters_df = 
  read_csv(
    "data/FAS_litters.csv", 
    skip = 5, 
    col_names = FALSE,
    na = "Low8")
litters_df
```
```{r}
# col_types: read_csv will guess the type of the data, but you can change it manually
litters_data = read_csv(file = "./data/FAS_litters.csv",
  col_types = cols(
    Group = col_character(),
    `Litter Number` = col_character(),
    `GD0 weight` = col_double(),
    `GD18 weight` = col_double(),
    `GD of Birth` = col_integer(),
    `Pups born alive` = col_integer(),
    `Pups dead @ birth` = col_integer(),
    `Pups survive` = col_integer()
  )
)
tail(litters_data)
```



