---
title: "tidy_data"
author: "Paula Wu"
date: "9/28/2021"
output: github_document
---

```{r, echo = FALSE, message = FALSE}
library(tidyverse)
library(readxl)
library(haven)
```

# pivot_longer
```{r}
pulse_df = 
  haven::read_sas("./data/public_pulse_data.sas7bdat") %>%
  janitor::clean_names()

pulse_df
```
Let's try to pivot: pivot longer
```{r}
# visit will be the type of visit, and dbi will store the values
pulse_tidy_df = 
  pulse_df %>% 
  pivot_longer(
    bdi_score_bl:bdi_score_12m,
    names_to = "visit", 
    values_to = "bdi",
    names_prefix = "bdi_score_"
  ) %>% 
  mutate(
    visit = replace(visit, visit == "bl", "00m"),
    visit = factor(visit)
  )
pulse_tidy_df
```

don't use gather(), use pivot_longer()

# pivot wider
make up a result data table
```{r}
analysis_df = 
  tibble(
    group = c("treatment", "treatment", "control", "control"),
    time = c("a", "b", "c", "d"),
    group_mean = c(4, 8, 3, 6)
  )
analysis_df %>% 
  pivot_wider(
    names_from = "time",
    values_from = "group_mean"
  ) %>% 
  knitr::kable()
```
Don't use spread(), use pivot_wider()
# bind rows
import the LotR movie words stuff
```{r}
fellowship_df = 
  read_excel("./data/LotR_Words.xlsx", range = "B3:D6") %>% 
  mutate(movie = "fellowship_rings")  # add an extra column "movie"
two_towers_df = 
  read_excel("./data/LotR_Words.xlsx", range = "F3:H6") %>% 
  mutate(movie = "tow_towers") 
return_df = 
  read_excel("./data/LotR_Words.xlsx", range = "J3:L6") %>% 
  mutate(movie = "return_of_the_king") 
lotr_df = 
  bind_rows(fellowship_df, two_towers_df, return_df) %>%  #stack all on top of each other
  janitor::clean_names() %>% 
  pivot_longer(
    female:male,
    names_to = "sex",
    values_to = "words"
  ) %>% 
  relocate(movie, .after = race) # just relocate movie after race column
```
# joins

Look at RAS data

```{r}
litters_df = 
  read_csv("data/FAS_litters.csv") %>% 
  janitor::clean_names() %>% 
  separate(group, into = c("dose", "day_of_tx"), 3) %>% # 3 letters and split
  relocate(litter_number) %>% 
  mutate(dose = str_to_lower(dose))

pups_df = 
  read_csv("data/FAS_pups.csv") %>% 
  janitor::clean_names() %>% 
  mutate(sex = recode(sex, `1` = "male", `2` = "female")) # recode, putting backticks is a way to force R to recognize the character
```

Let's join this up!
```{r}
# left join to pups
fas_df = 
  left_join(pups_df, litters_df, by = "litter_number") %>% # join by litter_number
  relocate(litter_number, dose, day_of_tx)
# fas_df %>% view
```





